services:
  api-lite:
    image: ghcr.io/jinpanda11/api-lite:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/data
    environment:
      - GIN_MODE=release
